kubectl create configmap config \
    --namespace dns  \
    --from-file bind.keys \
    --from-file db.cloudth.com \
    --from-file db.local \
    --from-file db.root \
    --from-file named.conf \
    --from-file named.conf.default-zones \
    --from-file named.conf.options 